version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - echo "Installing OS & PHP dependencies..."
      - dnf install -y php-zip php-mbstring php-xml php-cli unzip mariadb105
      - export HOME=/root
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - echo "Installing Composer dependencies..."
      - composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - echo "Installing NPM packages..."
      - rm -rf public/build
      - npm install
      - php artisan config:clear
      - php artisan cache:clear
      - composer update

  build:
    commands:
      - echo "Building front-end with Vite..."
      - npm run build

artifacts:
  files:
    - '**/*'
    - public/build/**/*
    - .ebextensions/**/*
    - .platform/**/*
    - .env.prod
    - vendor/**
    - bootstrap/cache/**

proxy:
  upload-artifacts: yes
  logs: yes
