version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - echo "Installing OS & PHP dependencies..."
      - dnf install -y php-zip php-mbstring php-xml php-cli unzip mariadb105
      - export HOME=/root
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - echo "[Slack] Sending pre_build notification..."
      - export SLACK_WEBHOOK="https://hooks.slack.com/services/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"
      - export BUILD_ID=$CODEBUILD_BUILD_ID
      - export PROJECT_NAME=$CODEBUILD_PROJECT_NAME
      - export BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F/ '{print $NF}')
      - export COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - export AWS_REGION=${AWS_REGION:-us-east-1}
      - |
        cat <<EOF | curl -X POST -H 'Content-type: application/json' --data-binary @- "$SLACK_WEBHOOK"
        {
          "text": ":hourglass_flowing_sand: Build started for *$PROJECT_NAME*",
          "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": ":hourglass_flowing_sand: *Build Started!*"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Branch:* $BRANCH\\n*Commit:* $COMMIT_ID"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Logs:* <https://$AWS_REGION.console.aws.amazon.com/codesuite/codebuild/projects/$PROJECT_NAME/build/$BUILD_ID/|View Logs>"}}
          ]
        }
        EOF

      - echo "Installing Composer dependencies..."
      - composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies || echo "Composer require failed" >> /tmp/error.log
      - composer install --no-interaction --prefer-dist --optimize-autoloader || echo "Composer install failed" >> /tmp/error.log
      - echo "Installing NPM packages..."
      - rm -rf public/build
      - npm install || echo "npm install failed" >> /tmp/error.log
      - php artisan config:clear
      - php artisan cache:clear
      - composer update || echo "Composer update failed" >> /tmp/error.log

  build:
    commands:
      - echo "Building front-end with Vite..."
      - npm run build || echo "Vite build failed" >> /tmp/error.log

  post_build:
    commands:
      - echo "[Slack] Sending build result..."
      - export SLACK_WEBHOOK="https://hooks.slack.com/services/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"
      - export BUILD_ID=$CODEBUILD_BUILD_ID
      - export PROJECT_NAME=$CODEBUILD_PROJECT_NAME
      - export BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F/ '{print $NF}')
      - export COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - export AWS_REGION=${AWS_REGION:-us-east-1}
      - export STATUS="SUCCESS"
      - export EB_ENV_NAME="SteamScoutsBeanstalkApplication-prod-env"
      - export EB_HEALTH=$(aws elasticbeanstalk describe-environment-health --environment-name "$EB_ENV_NAME" --attribute-names "Status" "Color" --query "Status" --output text 2>/dev/null || echo "Unknown")
      - |
        if [ -f /tmp/error.log ]; then
          STATUS="FAILED"
          ERROR_LOG=$(cat /tmp/error.log | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
        else
          ERROR_LOG="No errors detected."
        fi

        cat <<EOF | curl -X POST -H 'Content-type: application/json' --data-binary @- "$SLACK_WEBHOOK"
        {
          "text": ":rocket: *$PROJECT_NAME* Build Notification",
          "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Build Status:* *$STATUS*"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Branch:* $BRANCH\\n*Commit:* $COMMIT_ID\\n*Environment Health:* $EB_HEALTH"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Logs:* <https://$AWS_REGION.console.aws.amazon.com/codesuite/codebuild/projects/$PROJECT_NAME/build/$BUILD_ID/|View Build Logs>"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": "*Errors:*\\n\`\`\`$ERROR_LOG\`\`\`"}}
          ]
        }
        EOF

artifacts:
  files:
    - '**/*'
    - public/build/**/*
    - .ebextensions/**/*
    - .platform/**/*
    - .env.prod
    - vendor/**
    - bootstrap/cache/**

proxy:
  upload-artifacts: yes
  logs: yes
