version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18.x
    commands:
      - echo "Installing dependencies..."
      - dnf install -y mariadb105 unzip
      - export HOME=/root
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - echo "Installing Composer packages..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs 
      - echo "Installing NPM packages..."
      - rm -rf public/build
      - npm install
      - php artisan config:clear
      - php artisan cache:clear
      - composer update

  build:
    commands:
      - echo "Building front-end with Vite..."
      - npm run build

artifacts:
  files:
    - '**/*'
    - public/build/**/*
    - .ebextensions/**/*
    - .platform/**/*
    - .env.prod
    - vendor/**
    - bootstrap/cache/**
  name: build-$(date +%Y-%m-%dT%H-%M-%S).zip

proxy:
  upload-artifacts: yes
  logs: yes
