version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18.x
    commands:
      - echo "Installing required PHP extensions..."
      - dnf install -y php-zip php-mbstring php-xml php-cli unzip mariadb105
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - echo "Installing Composer dependencies..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - echo "Installing NPM dependencies..."
      - npm install

  build:
    commands:
      - echo "Building frontend..."
      - npm run build

artifacts:
  files:
    - '**/*'
    - public/build/**/*
    - .platform/**/*
    - .env.prod
    - vendor/**
    - bootstrap/cache/**
