name: Sync Laravel with Hostinger

on:
  push:
    branches:
      - main  # Trigger on any push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass  # Install sshpass to handle SSH login with password

      - name: Sync Files via SSH
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          
          cd domains/pyramakerz-artifacts.com/public_html/LMS/lms_pyramakerz/

          # Stash any local changes to avoid conflicts
          git stash || true

          # Pull the latest changes from the main branch
          git pull origin main --rebase || git reset --hard origin/main

          # Add, commit, and push any new or changed files
          git add .
          git commit -m "Sync server changes on $(date)" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

          # Install dependencies and optimize Laravel settings
          php composer.phar install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force

          exit
          EOF
