name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main  # Triggers automatically when code is pushed or merged to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass  # Use sshpass to handle password-based SSH

      - name: Deploy to Hostinger via SSH
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd domains/pyramakerz-artifacts.com/public_html/LMS/lms_pyramakerz/

          # Stash any uncommitted changes to avoid conflicts
          git stash || true

          # Pull the latest changes from the main branch
          git pull origin main --rebase || git reset --hard origin/main

          # Install dependencies and optimize Laravel configuration
          php composer.phar install --no-dev --prefer-dist --no-interaction --optimize-autoloader

          # Clear and cache Laravel configs, routes, and views
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Apply database migrations
          php artisan migrate --force

          exit
          EOF
